version: "2"

services:
  docker-mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mutant
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - docker-mysql:/var/lib/mysql
      - ./docker-mysql/init.sql:/docker-entrypoint-initdocker-mysql.d/init.sql

  is-mutant-service:
    image: devcaiquemacedo/image-api-is-mutant:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - "docker-mysql"
    restart: always

volumes:
  docker-mysql:
    driver: local