server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-06.cleardb.net:3306/heroku_5ce4075ccd6699f?reconnect=true&createDatabaseIfNotExist=true
    username: b7b9a583c82207
    password: 1a43c501
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
